version: '3.1'

services:
  postgres-compose:
    image: postgres
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: woflgan
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - wolfgan:/var/lib/postgres
volumes: 
  wolfgan: